[package]
name = "fledgeos-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bootloader = "0.10.12"
x86_64 = "0.14.9"

[package.metadata.bootimage]
default-target = "fledge.json"
